import React from 'react';
import './Style.css';
const About=()=>{

    return(<>
    <h1>About</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione culpa pariatur earum neque suscipit laudantium, ab deleniti commodi exercitationem beatae iure eius maiores? Modi soluta, in debitis quaerat necessitatibus fugiat. Aspernatur doloremque nisi, natus nulla ea sint, incidunt accusamus quo non sapiente magni harum veniam eveniet atque quasi asperiores, commodi facere debitis error animi! Consequuntur expedita officiis, incidunt obcaecati ea et temporibus ullam vel animi distinctio in laudantium enim alias sed quibusdam dolor nemo nulla. Repellendus asperiores quod delectus reprehenderit eveniet praesentium nobis quaerat quam assumenda eaque? Corrupti, facilis suscipit sequi iste eaque aspernatur voluptatibus deserunt unde impedit ex fuga! Sunt et sint vel harum deleniti saepe ut nemo blanditiis iusto atque doloribus quos fugiat vero culpa recusandae minima ratione perferendis, dolores eius. Nihil iure sunt mollitia, voluptatem corrupti similique sequi vel minus, culpa aliquam est vero a corporis repudiandae atque ab? Veritatis, earum laborum. Nulla similique quod inventore est eligendi optio quas incidunt consequuntur eum necessitatibus, magnam error in animi hic fugiat aliquam a voluptatum commodi at. Facilis odio atque placeat unde, molestias neque veniam nam ut voluptate laboriosam impedit, pariatur maiores minima natus? Odio fuga, harum quia quisquam est neque libero aspernatur, veniam commodi iste consequatur, iure ipsa.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione culpa pariatur earum neque suscipit laudantium, ab deleniti commodi exercitationem beatae iure eius maiores? Modi soluta, in debitis quaerat necessitatibus fugiat. Aspernatur doloremque nisi, natus nulla ea sint, incidunt accusamus quo non sapiente magni harum veniam eveniet atque quasi asperiores, commodi facere debitis error animi! Consequuntur expedita officiis, incidunt obcaecati ea et temporibus ullam vel animi distinctio in laudantium enim alias sed quibusdam dolor nemo nulla. Repellendus asperiores quod delectus reprehenderit eveniet praesentium nobis quaerat quam assumenda eaque? Corrupti, facilis suscipit sequi iste eaque aspernatur voluptatibus deserunt unde impedit ex fuga! Sunt et sint vel harum deleniti saepe ut nemo blanditiis iusto atque doloribus quos fugiat vero culpa recusandae minima ratione perferendis, dolores eius. Nihil iure sunt mollitia, voluptatem corrupti similique sequi vel minus, culpa aliquam est vero a corporis repudiandae atque ab? Veritatis, earum laborum. Nulla similique quod inventore est eligendi optio quas incidunt consequuntur eum necessitatibus, magnam error in animi hic fugiat aliquam a voluptatum commodi at. Facilis odio atque placeat unde, molestias neque veniam nam ut voluptate laboriosam impedit, pariatur maiores minima natus? Odio fuga, harum quia quisquam est neque libero aspernatur, veniam commodi iste consequatur, iure ipsa.</p>
    </>);

}

export default About;